# https://woodruffw.github.io/zizmor/
rules:
  unpinned-uses:
    config:
      policies:
        actions/*: hash-pin
        github/codeql-action/*: hash-pin
        codecov/*: hash-pin
        astral-sh/setup-uv: hash-pin
        pypa/gh-action-pypi-publish: hash-pin
        ncipollo/release-action: hash-pin
        release-flow/keep-a-changelog-action: hash-pin
        j178/prek-action: hash-pin
