# SPDX-FileCopyrightText: 2023-present Trenton H <rda0128ou@mozmail.com>
#
# SPDX-License-Identifier: MPL-2.0
"""
Tests for in-band parse failures, which Tika 4 reports on an HTTP 200.

Tika 3.x returned 500 when the container parser failed. Tika 4 returns 200 with
the stack trace in tk:exception:container-exception and no tk:content at all, so
without these tests a failed parse is indistinguishable from an empty document.

These run against a real tika-server; the corrupt fixture is generated by
truncating a valid .docx so no binary sample needs committing.
"""

from __future__ import annotations

import zipfile
from typing import TYPE_CHECKING
from typing import ClassVar

import pytest

from tika_client.client import AsyncTikaClient
from tika_client.client import TikaClient
from tika_client.data_models import TikaKey
from tika_client.data_models import TikaResponse
from tika_client.data_models import TikaResponseList
from tika_client.exceptions import TikaContainerParseError
from tika_client.exceptions import TikaEmbeddedParseError
from tika_client.exceptions import TikaError
from tika_client.exceptions import TikaParseError
from tika_client.exceptions import TikaParseErrorGroup

if TYPE_CHECKING:
    from pathlib import Path

    from pytest_httpx import HTTPXMock


@pytest.fixture(scope="session")
def corrupt_docx_file(samples_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A .docx truncated mid-archive, which Tika detects as OOXML but cannot open."""
    truncated = (samples_dir / "sample.docx").read_bytes()[:2000]
    path = tmp_path_factory.mktemp("corrupt") / "corrupt.docx"
    path.write_bytes(truncated)
    return path


@pytest.fixture(scope="session")
def corrupt_odt_file(samples_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """An .odt truncated so the container parser itself fails, unlike the docx which salvages."""
    truncated = (samples_dir / "sample.odt").read_bytes()[:4000]
    path = tmp_path_factory.mktemp("corrupt") / "corrupt.odt"
    path.write_bytes(truncated)
    return path


@pytest.fixture(scope="session")
def zip_with_broken_member(samples_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> Path:
    """
    A zip whose container parses cleanly but which holds one unreadable document.

    Tika extracts the good member and reports the bad one via an embedded exception, so the
    content looks complete: the failed member's filename appears with no text after it.
    """
    work = tmp_path_factory.mktemp("mixed")
    good = work / "good.txt"
    good.write_text("this attachment is perfectly readable")
    broken = work / "broken.docx"
    broken.write_bytes((samples_dir / "sample.docx").read_bytes()[:2000])

    archive = work / "mixed.zip"
    with zipfile.ZipFile(archive, "w") as handle:
        handle.write(good, "good.txt")
        handle.write(broken, "broken.docx")
    return archive


class TestEmbeddedFailureOnSingleDocument:
    """
    An unreadable attachment must not pass silently through the single-document endpoints.

    Tika returns 200 with the good content extracted and the failed member's text simply
    absent, so nothing in the payload marks the loss.
    """

    def test_embedded_failure_raises(self, tika_client: TikaClient, zip_with_broken_member: Path) -> None:
        """The one silent partial-data path on tika.*: an attachment fails, content looks fine."""
        with pytest.raises(TikaEmbeddedParseError):
            tika_client.tika.as_text.from_file(zip_with_broken_member)

    def test_partial_content_survives_the_raise(
        self,
        tika_client: TikaClient,
        zip_with_broken_member: Path,
    ) -> None:
        """Raising must not discard what was extracted, or best-effort callers lose out."""
        with pytest.raises(TikaEmbeddedParseError) as err:
            tika_client.tika.as_text.from_file(zip_with_broken_member)

        assert err.value.partial.content is not None
        assert "perfectly readable" in err.value.partial.content
        assert err.value.partial.embedded_exception is not None

    def test_rmeta_still_does_not_raise(self, tika_client: TikaClient, zip_with_broken_member: Path) -> None:
        """The list form is unchanged: raising there would discard entries that parsed."""
        results = tika_client.rmeta.as_text.from_file(zip_with_broken_member)

        assert results.has_parse_errors


class TestContainerParseException:
    def test_container_exception_raises(self, tika_client: TikaClient, corrupt_docx_file: Path) -> None:
        """A container-level parse failure raises instead of returning empty content."""
        with pytest.raises(TikaContainerParseError):
            tika_client.tika.as_text.from_file(corrupt_docx_file)


class TestRecursiveMetadataNeverRaises:
    """
    /rmeta returns one entry per embedded document, so a failure is rarely total.

    Raising would discard the entries that parsed, so these failures are exposed
    on the response instead.
    """

    def test_embedded_failure_does_not_raise(self, tika_client: TikaClient, corrupt_docx_file: Path) -> None:
        """An embedded document failing leaves the successfully parsed entries reachable."""
        result = tika_client.rmeta.as_text.from_file(corrupt_docx_file)

        assert result.has_parse_errors
        assert result[0].parse_exception is None
        assert any(entry.parse_exception is not None for entry in result)

    def test_container_failure_does_not_raise(self, tika_client: TikaClient, corrupt_odt_file: Path) -> None:
        """Even a container-level failure is exposed rather than raised, unlike the /tika path."""
        result = tika_client.rmeta.as_text.from_file(corrupt_odt_file)

        assert result.has_parse_errors
        assert result[0].parse_exception is not None
        assert "Exception" in result[0].parse_exception


class TestRaiseForParseStatus:
    """Opt-in raising, mirroring how httpx defers raise_for_status to the caller."""

    def test_noop_when_document_parsed(
        self,
        tika_client: TikaClient,
        sample_google_docs_to_docx_file: Path,
    ) -> None:
        """A document that parsed cleanly does not raise."""
        result = tika_client.rmeta.as_text.from_file(sample_google_docs_to_docx_file)

        # Calling is the assertion: either of these raising fails the test.
        result.raise_for_parse_status()
        result[0].raise_for_parse_status()

    def test_embedded_failure_raises_embedded_error(
        self,
        tika_client: TikaClient,
        corrupt_docx_file: Path,
    ) -> None:
        """An embedded document failure raises the embedded subclass, not the container one."""
        result = tika_client.rmeta.as_text.from_file(corrupt_docx_file)
        failed = next(entry for entry in result if entry.parse_exception is not None)

        with pytest.raises(TikaEmbeddedParseError):
            failed.raise_for_parse_status()

    def test_container_failure_raises_container_error(
        self,
        tika_client: TikaClient,
        corrupt_odt_file: Path,
    ) -> None:
        """A container-level failure raises the container subclass."""
        result = tika_client.rmeta.as_text.from_file(corrupt_odt_file)

        with pytest.raises(TikaContainerParseError):
            result[0].raise_for_parse_status()

    def test_list_raises_group_of_every_failure(self, tika_client: TikaClient, corrupt_docx_file: Path) -> None:
        """Raising over a list groups every failed document so none are hidden."""
        result = tika_client.rmeta.as_text.from_file(corrupt_docx_file)

        # Hardcoded from observed apache/tika:4.0.0 behaviour: the truncated .docx yields
        # five entries with exactly one failure. Deriving the count from parse_exception,
        # the attribute under test, would let over-detection inflate both sides in
        # lockstep and still pass.
        assert len(result) == 5
        with pytest.raises(TikaParseErrorGroup) as exc_info:
            result.raise_for_parse_status()

        assert len(exc_info.value.exceptions) == 1
        assert all(isinstance(exc, TikaParseError) for exc in exc_info.value.exceptions)

    def test_group_is_catchable_as_tika_error(self, tika_client: TikaClient, corrupt_docx_file: Path) -> None:
        """The group must satisfy the TikaError contract, or the obvious handler misses it."""
        result = tika_client.rmeta.as_text.from_file(corrupt_docx_file)

        with pytest.raises(TikaError):
            result.raise_for_parse_status()


class TestSingleDocumentEndpointsRaise:
    """
    Mocked coverage of the raising contract for paths the live tests do not reach.

    These construct a client directly instead of using the tika_client fixture, which
    depends on the container fixture, so they run on a CI leg without Docker.
    """

    CONTAINER_FAILURE: ClassVar[dict[str, str]] = {
        TikaKey.ContentType: "application/vnd.oasis.opendocument.text",
        TikaKey.ContainerException: "org.apache.tika.exception.TikaException: Error opening file",
    }

    def test_metadata_from_file_raises(
        self,
        sample_libre_office_writer_file: Path,
        httpx_mock: HTTPXMock,
    ) -> None:
        """/meta shares decoded_response with /tika, so a container failure must raise there too."""
        httpx_mock.add_response(json=self.CONTAINER_FAILURE)

        with TikaClient(tika_url="http://tika.invalid") as client, pytest.raises(TikaContainerParseError):
            client.metadata.from_file(sample_libre_office_writer_file)

    async def test_async_tika_from_file_raises(
        self,
        sample_libre_office_writer_file: Path,
        httpx_mock: HTTPXMock,
    ) -> None:
        """The async paths share decoded_response, so they raise identically."""
        httpx_mock.add_response(json=self.CONTAINER_FAILURE)

        async with AsyncTikaClient(tika_url="http://tika.invalid") as client:
            with pytest.raises(TikaContainerParseError):
                await client.tika.as_text.from_file(sample_libre_office_writer_file)

    def test_both_keys_present_prefers_the_container_failure(self) -> None:
        """A failed container makes the embedded failure moot, so it takes precedence."""
        response = TikaResponse(
            {
                **self.CONTAINER_FAILURE,
                TikaKey.EmbeddedException: "org.apache.tika.exception.TikaException: embedded",
            },
        )

        assert response.parse_exception == self.CONTAINER_FAILURE[TikaKey.ContainerException]
        assert response.container_exception == self.CONTAINER_FAILURE[TikaKey.ContainerException]
        assert response.embedded_exception == "org.apache.tika.exception.TikaException: embedded"
        with pytest.raises(TikaContainerParseError):
            response.raise_for_parse_status()

    def test_embedded_only_raises_the_embedded_error(self) -> None:
        """With no container failure the embedded one is what surfaces."""
        response = TikaResponse(
            {
                TikaKey.ContentType: "application/zip",
                TikaKey.EmbeddedException: "org.apache.tika.exception.TikaException: embedded",
            },
        )

        assert response.container_exception is None
        with pytest.raises(TikaEmbeddedParseError):
            response.raise_for_parse_status()


class TestMetadataIgnoresEmbeddedFailures:
    """
    /meta returns container metadata only, so an embedded failure does not affect its answer.

    Raising would discard metadata that is complete with respect to what was asked for. A
    live tika-server does not send the embedded key on /meta at all, so this is enforced by
    construction rather than in reaction to observed behaviour.
    """

    def test_embedded_failure_does_not_raise(
        self,
        sample_libre_office_writer_file: Path,
        httpx_mock: HTTPXMock,
    ) -> None:
        """An embedded failure leaves the container metadata usable."""
        httpx_mock.add_response(
            json={
                TikaKey.ContentType: "application/zip",
                TikaKey.EmbeddedException: "org.apache.tika.exception.TikaException: embedded",
            },
        )

        with TikaClient(tika_url="http://tika.invalid") as client:
            result = client.metadata.from_file(sample_libre_office_writer_file)

        assert result.type == "application/zip"
        assert result.embedded_exception is not None

    def test_container_failure_still_raises(
        self,
        sample_libre_office_writer_file: Path,
        httpx_mock: HTTPXMock,
    ) -> None:
        """A container failure means the metadata itself is untrustworthy, so it still raises."""
        httpx_mock.add_response(
            json={TikaKey.ContainerException: "org.apache.tika.exception.TikaException: boom"},
        )

        with TikaClient(tika_url="http://tika.invalid") as client, pytest.raises(TikaContainerParseError):
            client.metadata.from_file(sample_libre_office_writer_file)


class TestTaskDeadlineReached:
    """
    Tika 4 truncates rather than failing when a parse exceeds its deadline.

    PARTIAL_TIMEOUT maps to 200 on every endpoint with whatever content was extracted
    before the deadline, so this is a success that is merely incomplete. Raising would
    discard usable content, but leaving it unreported would make truncation silent.
    """

    def test_deadline_reached_marks_truncated_without_raising(self) -> None:
        """Truncated content is still returned, flagged rather than raised."""
        response = TikaResponse(
            {
                TikaKey.ContentType: "application/pdf",
                TikaKey.TaskDeadlineReached: "true",
                TikaKey.Content: "as far as it got",
            },
        )

        assert response.truncated is True
        assert response.parse_exception is None
        assert response.content == "as far as it got"
        # Truncation is not a parse failure, so this must not raise.
        response.raise_for_parse_status()

    def test_absent_deadline_key_is_not_truncated(self) -> None:
        """A complete parse reports truncated as False rather than None."""
        response = TikaResponse({TikaKey.ContentType: "application/pdf", TikaKey.Content: "all of it"})

        assert response.truncated is False

    def test_explicit_false_is_not_truncated(self) -> None:
        """An explicit false is honoured rather than treated as presence."""
        response = TikaResponse(
            {TikaKey.ContentType: "application/pdf", TikaKey.TaskDeadlineReached: "false"},
        )

        assert response.truncated is False

    @pytest.mark.parametrize(
        "value",
        [
            pytest.param(["true"], id="multi-valued-list"),
            pytest.param("2026-08-27T10:00:00Z", id="timestamp"),
            pytest.param("Task deadline reached after 60000ms", id="message"),
        ],
    )
    def test_unexpected_value_shapes_still_report_truncated(self, value: object) -> None:
        """
        The wire format is unconfirmed, so presence is the signal.

        The key was read out of TikaCoreProperties rather than observed on the wire, and
        its two siblings in the tk:exception: namespace carry stack traces rather than
        booleans. Failing closed here would recreate the silent truncation this exists
        to prevent.
        """
        response = TikaResponse(
            {TikaKey.ContentType: "application/pdf", TikaKey.TaskDeadlineReached: value},
        )

        assert response.truncated is True

    def test_list_reports_truncation_from_any_entry(self) -> None:
        """Callers guarding on has_parse_errors alone would otherwise ingest truncated content."""
        results = TikaResponseList(
            [
                TikaResponse({TikaKey.ContentType: "application/pdf"}),
                TikaResponse(
                    {TikaKey.ContentType: "application/pdf", TikaKey.TaskDeadlineReached: "true"},
                ),
            ],
        )

        assert results.truncated is True
        assert results.has_parse_errors is False

    def test_list_without_truncation_reports_false(self) -> None:
        """A complete set of documents reports no truncation."""
        results = TikaResponseList([TikaResponse({TikaKey.ContentType: "application/pdf"})])

        assert results.truncated is False
